### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by coderstory** [nekohasekai/SagerNet#11]
1.先复制一个torjan的订阅地址 然后选择从剪贴板导入 没有识别成订阅地址
列表里点击修改图标后FC 出现空指针 username must not be null 
没有正确识别 也没有校验

2.设置里的路由模式 选择 绕过局域网和大陆地址  并重新连接
  在浏览器中使用百度查询ip 出现的ip是服务器的ip

3.logo 有点反人类

4.log里出现敏感信息 分享不方便 【ip  port password etc】

5.开启vpn的时候 可以考虑可以修改设置 无操作延迟几秒后重新连接 或者加一个重启服务的按钮提示

6.扫描中国应用 建议改成 分析中国应用并勾选  
  以及分析时候的弹窗 随着显示的应用增多 不断被拉长 最后还直接消失了 这操作有点奇怪

7.分应用代理设置界面 关闭按钮对应打开按钮，那么 绕过按钮对应的放行按钮在哪？ 第一次点了之后再点没反应

[SagerNet-4509470032590749279.log](https://github.com/nekohasekai/SagerNet/files/6383684/SagerNet-4509470032590749279.log)

**Comment by coderstory** [comment]
中国应用的例外app
edge 微软的浏览器
一些工具类，比如xposed插件 rikka的存储空间隔离 搞机助手等

**Comment by nekohasekai** [comment]
1. 订阅地址去组页添加, 从剪切板导入只识别节点.
2. HTTP 配置的问题已经修复了
3. 关于 edge, 我刚刚测试了一下, play 版是没有判定的, 你用的是什么版本?

**Comment by nekohasekai** [comment]
另外, 存储重定向的 play 版也是不会被判定的 (可能是多了什么支付组件, 但能在墙内支付这很明显不需要代理)

**Comment by nekohasekai** [comment]
4. 分应用里 "开启" 是白名单模式, "绕过" 是黑名单模式.

**Comment by Potterli20** [comment]
> 
> 
>     1. 订阅地址去组页添加, 从剪切板导入只识别节点.
> 
>     2. HTTP 配置的问题已经修复了
> 
>     3. 关于 edge, 我刚刚测试了一下, play 版是没有判定的, 你用的是什么版本?

现在我有个问题，我用vmess+http伪装无法连接
