### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Solo-Dance** [nekohasekai/SagerNet#15]
您好，试用了一下SagerNet，感觉很棒。我有几个想法😃
1、默认开启UDP
2、可以自己替换GEO资源文件
还有就是希望后续可以加入xray的支持，目前数据表示xray更好用些

**Comment by Potterli20** [comment]
> 
> 
> 您好，试用了一下SagerNet，感觉很棒。我有几个想法😃
> 1、默认开启UDP
> 2、可以自己替换GEO资源文件
> 还有就是希望后续可以加入xray的支持，目前数据表示xray更好用些

他不加哈哈哈
