### ISSUE TITLE
升级至beta8导致订阅组全部丢失

### ISSUE THREAD

**Issue by ChirmyRam** [nekohasekai/SagerNet#25]
**Describe the bug**
升级至beta8导致订阅组全部丢失

**To Reproduce**
从beta7升至beta8

**Smartphone (please complete the following information):**
 - Device: realmeX
 - OS: Android10
 - 
log:
SagerNet 0.1-beta8 (8) on API 29
ABI arm64-v8a (arm64-v8a, armeabi-v7a, armeabi)

**Comment by cubercsl** [comment]
从更新频道的推送来看，这次更新为不兼容更新，将会丢失节点和订阅数据 (设置不会)。

报告的行为应该符合预期。
